# Generated by Django 3.2 on 2021-04-20 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nRighe', models.IntegerField()),
                ('nColonne', models.IntegerField()),
                ('player1point', models.IntegerField()),
                ('player2point', models.IntegerField()),
                ('status', models.IntegerField()),
                ('dateStart', models.DateTimeField()),
                ('dateLastUpdate', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexRighe', models.IntegerField()),
                ('indexColonne', models.IntegerField()),
                ('playerType', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Python.game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
